// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StreamApiWatcher is an autogenerated mock type for the StreamApiWatcher type
type StreamApiWatcher struct {
	mock.Mock
}

// GetResult provides a mock function with given fields:
func (_m *StreamApiWatcher) GetResult() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *StreamApiWatcher) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *StreamApiWatcher) Stop() {
	_m.Called()
}
