// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	base "github.com/couchbase/goxdcr/v8/base"
	mock "github.com/stretchr/testify/mock"
)

// TargetCollectionInfoPoolIface is an autogenerated mock type for the TargetCollectionInfoPoolIface type
type TargetCollectionInfoPoolIface struct {
	mock.Mock
}

type TargetCollectionInfoPoolIface_Expecter struct {
	mock *mock.Mock
}

func (_m *TargetCollectionInfoPoolIface) EXPECT() *TargetCollectionInfoPoolIface_Expecter {
	return &TargetCollectionInfoPoolIface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields:
func (_m *TargetCollectionInfoPoolIface) Get() *base.TargetCollectionInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *base.TargetCollectionInfo
	if rf, ok := ret.Get(0).(func() *base.TargetCollectionInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*base.TargetCollectionInfo)
		}
	}

	return r0
}

// TargetCollectionInfoPoolIface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TargetCollectionInfoPoolIface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *TargetCollectionInfoPoolIface_Expecter) Get() *TargetCollectionInfoPoolIface_Get_Call {
	return &TargetCollectionInfoPoolIface_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *TargetCollectionInfoPoolIface_Get_Call) Run(run func()) *TargetCollectionInfoPoolIface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TargetCollectionInfoPoolIface_Get_Call) Return(_a0 *base.TargetCollectionInfo) *TargetCollectionInfoPoolIface_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TargetCollectionInfoPoolIface_Get_Call) RunAndReturn(run func() *base.TargetCollectionInfo) *TargetCollectionInfoPoolIface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: _a0
func (_m *TargetCollectionInfoPoolIface) Put(_a0 *base.TargetCollectionInfo) {
	_m.Called(_a0)
}

// TargetCollectionInfoPoolIface_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type TargetCollectionInfoPoolIface_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - _a0 *base.TargetCollectionInfo
func (_e *TargetCollectionInfoPoolIface_Expecter) Put(_a0 interface{}) *TargetCollectionInfoPoolIface_Put_Call {
	return &TargetCollectionInfoPoolIface_Put_Call{Call: _e.mock.On("Put", _a0)}
}

func (_c *TargetCollectionInfoPoolIface_Put_Call) Run(run func(_a0 *base.TargetCollectionInfo)) *TargetCollectionInfoPoolIface_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*base.TargetCollectionInfo))
	})
	return _c
}

func (_c *TargetCollectionInfoPoolIface_Put_Call) Return() *TargetCollectionInfoPoolIface_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *TargetCollectionInfoPoolIface_Put_Call) RunAndReturn(run func(*base.TargetCollectionInfo)) *TargetCollectionInfoPoolIface_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewTargetCollectionInfoPoolIface creates a new instance of TargetCollectionInfoPoolIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetCollectionInfoPoolIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetCollectionInfoPoolIface {
	mock := &TargetCollectionInfoPoolIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
