// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	conflictlog "github.com/couchbase/goxdcr/v8/base/conflictlog"
	mock "github.com/stretchr/testify/mock"
)

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

type Connection_Expecter struct {
	mock *mock.Mock
}

func (_m *Connection) EXPECT() *Connection_Expecter {
	return &Connection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Connection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Connection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Connection_Expecter) Close() *Connection_Close_Call {
	return &Connection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Connection_Close_Call) Run(run func()) *Connection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Close_Call) Return(_a0 error) *Connection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connection_Close_Call) RunAndReturn(run func() error) *Connection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with no fields
func (_m *Connection) Id() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Connection_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type Connection_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *Connection_Expecter) Id() *Connection_Id_Call {
	return &Connection_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *Connection_Id_Call) Run(run func()) *Connection_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Id_Call) Return(_a0 int64) *Connection_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Connection_Id_Call) RunAndReturn(run func() int64) *Connection_Id_Call {
	_c.Call.Return(run)
	return _c
}

// SetMeta provides a mock function with given fields: key, val, dataType, target
func (_m *Connection) SetMeta(key string, val []byte, dataType uint8, target conflictlog.Target) error {
	ret := _m.Called(key, val, dataType, target)

	if len(ret) == 0 {
		panic("no return value specified for SetMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, uint8, conflictlog.Target) error); ok {
		r0 = rf(key, val, dataType, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connection_SetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMeta'
type Connection_SetMeta_Call struct {
	*mock.Call
}

// SetMeta is a helper method to define mock.On call
//   - key string
//   - val []byte
//   - dataType uint8
//   - target conflictlog.Target
func (_e *Connection_Expecter) SetMeta(key interface{}, val interface{}, dataType interface{}, target interface{}) *Connection_SetMeta_Call {
	return &Connection_SetMeta_Call{Call: _e.mock.On("SetMeta", key, val, dataType, target)}
}

func (_c *Connection_SetMeta_Call) Run(run func(key string, val []byte, dataType uint8, target conflictlog.Target)) *Connection_SetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(uint8), args[3].(conflictlog.Target))
	})
	return _c
}

func (_c *Connection_SetMeta_Call) Return(err error) *Connection_SetMeta_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Connection_SetMeta_Call) RunAndReturn(run func(string, []byte, uint8, conflictlog.Target) error) *Connection_SetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnection creates a new instance of Connection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connection {
	mock := &Connection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
