// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	common "github.com/couchbase/goxdcr/common"
	mock "github.com/stretchr/testify/mock"
)

// CheckpointFunc is an autogenerated mock type for the CheckpointFunc type
type CheckpointFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CheckpointFunc) Execute(_a0 common.Pipeline) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.Pipeline) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCheckpointFunc creates a new instance of CheckpointFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckpointFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckpointFunc {
	mock := &CheckpointFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
