// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	common "github.com/couchbase/goxdcr/v8/common"
	mock "github.com/stretchr/testify/mock"

	peerToPeer "github.com/couchbase/goxdcr/v8/peerToPeer"
)

// VBMasterCheckFunc is an autogenerated mock type for the VBMasterCheckFunc type
type VBMasterCheckFunc struct {
	mock.Mock
}

type VBMasterCheckFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *VBMasterCheckFunc) EXPECT() *VBMasterCheckFunc_Expecter {
	return &VBMasterCheckFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *VBMasterCheckFunc) Execute(_a0 common.Pipeline) (map[string]*peerToPeer.VBMasterCheckResp, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 map[string]*peerToPeer.VBMasterCheckResp
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Pipeline) (map[string]*peerToPeer.VBMasterCheckResp, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(common.Pipeline) map[string]*peerToPeer.VBMasterCheckResp); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*peerToPeer.VBMasterCheckResp)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Pipeline) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VBMasterCheckFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type VBMasterCheckFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 common.Pipeline
func (_e *VBMasterCheckFunc_Expecter) Execute(_a0 interface{}) *VBMasterCheckFunc_Execute_Call {
	return &VBMasterCheckFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *VBMasterCheckFunc_Execute_Call) Run(run func(_a0 common.Pipeline)) *VBMasterCheckFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Pipeline))
	})
	return _c
}

func (_c *VBMasterCheckFunc_Execute_Call) Return(_a0 map[string]*peerToPeer.VBMasterCheckResp, _a1 error) *VBMasterCheckFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VBMasterCheckFunc_Execute_Call) RunAndReturn(run func(common.Pipeline) (map[string]*peerToPeer.VBMasterCheckResp, error)) *VBMasterCheckFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewVBMasterCheckFunc creates a new instance of VBMasterCheckFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVBMasterCheckFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *VBMasterCheckFunc {
	mock := &VBMasterCheckFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
