// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	metadata "github.com/couchbase/goxdcr/metadata"
	mock "github.com/stretchr/testify/mock"
)

// ReplicationSpecGetter is an autogenerated mock type for the ReplicationSpecGetter type
type ReplicationSpecGetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: specId
func (_m *ReplicationSpecGetter) Execute(specId string) (*metadata.ReplicationSpecification, error) {
	ret := _m.Called(specId)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *metadata.ReplicationSpecification
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*metadata.ReplicationSpecification, error)); ok {
		return rf(specId)
	}
	if rf, ok := ret.Get(0).(func(string) *metadata.ReplicationSpecification); ok {
		r0 = rf(specId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.ReplicationSpecification)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(specId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReplicationSpecGetter creates a new instance of ReplicationSpecGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReplicationSpecGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReplicationSpecGetter {
	mock := &ReplicationSpecGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
