// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	metadata "github.com/couchbase/goxdcr/v8/metadata"

	mock "github.com/stretchr/testify/mock"
)

// RemoteAgentMetadata is an autogenerated mock type for the RemoteAgentMetadata type
type RemoteAgentMetadata struct {
	mock.Mock
}

type RemoteAgentMetadata_Expecter struct {
	mock *mock.Mock
}

func (_m *RemoteAgentMetadata) EXPECT() *RemoteAgentMetadata_Expecter {
	return &RemoteAgentMetadata_Expecter{mock: &_m.Mock}
}

// GetCapability provides a mock function with no fields
func (_m *RemoteAgentMetadata) GetCapability() (metadata.Capability, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCapability")
	}

	var r0 metadata.Capability
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.Capability, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.Capability); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(metadata.Capability)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteAgentMetadata_GetCapability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapability'
type RemoteAgentMetadata_GetCapability_Call struct {
	*mock.Call
}

// GetCapability is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) GetCapability() *RemoteAgentMetadata_GetCapability_Call {
	return &RemoteAgentMetadata_GetCapability_Call{Call: _e.mock.On("GetCapability")}
}

func (_c *RemoteAgentMetadata_GetCapability_Call) Run(run func()) *RemoteAgentMetadata_GetCapability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_GetCapability_Call) Return(_a0 metadata.Capability, _a1 error) *RemoteAgentMetadata_GetCapability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteAgentMetadata_GetCapability_Call) RunAndReturn(run func() (metadata.Capability, error)) *RemoteAgentMetadata_GetCapability_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionStringForCAPIRemoteCluster provides a mock function with no fields
func (_m *RemoteAgentMetadata) GetConnectionStringForCAPIRemoteCluster() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStringForCAPIRemoteCluster")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStringForCAPIRemoteCluster'
type RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call struct {
	*mock.Call
}

// GetConnectionStringForCAPIRemoteCluster is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) GetConnectionStringForCAPIRemoteCluster() *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call {
	return &RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call{Call: _e.mock.On("GetConnectionStringForCAPIRemoteCluster")}
}

func (_c *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call) Run(run func()) *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call) Return(_a0 string, _a1 error) *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call) RunAndReturn(run func() (string, error)) *RemoteAgentMetadata_GetConnectionStringForCAPIRemoteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceAndStatusClone provides a mock function with no fields
func (_m *RemoteAgentMetadata) GetReferenceAndStatusClone() *metadata.RemoteClusterReference {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceAndStatusClone")
	}

	var r0 *metadata.RemoteClusterReference
	if rf, ok := ret.Get(0).(func() *metadata.RemoteClusterReference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.RemoteClusterReference)
		}
	}

	return r0
}

// RemoteAgentMetadata_GetReferenceAndStatusClone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceAndStatusClone'
type RemoteAgentMetadata_GetReferenceAndStatusClone_Call struct {
	*mock.Call
}

// GetReferenceAndStatusClone is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) GetReferenceAndStatusClone() *RemoteAgentMetadata_GetReferenceAndStatusClone_Call {
	return &RemoteAgentMetadata_GetReferenceAndStatusClone_Call{Call: _e.mock.On("GetReferenceAndStatusClone")}
}

func (_c *RemoteAgentMetadata_GetReferenceAndStatusClone_Call) Run(run func()) *RemoteAgentMetadata_GetReferenceAndStatusClone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_GetReferenceAndStatusClone_Call) Return(_a0 *metadata.RemoteClusterReference) *RemoteAgentMetadata_GetReferenceAndStatusClone_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RemoteAgentMetadata_GetReferenceAndStatusClone_Call) RunAndReturn(run func() *metadata.RemoteClusterReference) *RemoteAgentMetadata_GetReferenceAndStatusClone_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceClone provides a mock function with given fields: refresh
func (_m *RemoteAgentMetadata) GetReferenceClone(refresh bool) (*metadata.RemoteClusterReference, error) {
	ret := _m.Called(refresh)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceClone")
	}

	var r0 *metadata.RemoteClusterReference
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) (*metadata.RemoteClusterReference, error)); ok {
		return rf(refresh)
	}
	if rf, ok := ret.Get(0).(func(bool) *metadata.RemoteClusterReference); ok {
		r0 = rf(refresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.RemoteClusterReference)
		}
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(refresh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteAgentMetadata_GetReferenceClone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceClone'
type RemoteAgentMetadata_GetReferenceClone_Call struct {
	*mock.Call
}

// GetReferenceClone is a helper method to define mock.On call
//   - refresh bool
func (_e *RemoteAgentMetadata_Expecter) GetReferenceClone(refresh interface{}) *RemoteAgentMetadata_GetReferenceClone_Call {
	return &RemoteAgentMetadata_GetReferenceClone_Call{Call: _e.mock.On("GetReferenceClone", refresh)}
}

func (_c *RemoteAgentMetadata_GetReferenceClone_Call) Run(run func(refresh bool)) *RemoteAgentMetadata_GetReferenceClone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *RemoteAgentMetadata_GetReferenceClone_Call) Return(_a0 *metadata.RemoteClusterReference, _a1 error) *RemoteAgentMetadata_GetReferenceClone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteAgentMetadata_GetReferenceClone_Call) RunAndReturn(run func(bool) (*metadata.RemoteClusterReference, error)) *RemoteAgentMetadata_GetReferenceClone_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with no fields
func (_m *RemoteAgentMetadata) Id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoteAgentMetadata_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type RemoteAgentMetadata_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) Id() *RemoteAgentMetadata_Id_Call {
	return &RemoteAgentMetadata_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *RemoteAgentMetadata_Id_Call) Run(run func()) *RemoteAgentMetadata_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_Id_Call) Return(_a0 string) *RemoteAgentMetadata_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RemoteAgentMetadata_Id_Call) RunAndReturn(run func() string) *RemoteAgentMetadata_Id_Call {
	_c.Call.Return(run)
	return _c
}

// IsSame provides a mock function with given fields: ref
func (_m *RemoteAgentMetadata) IsSame(ref *metadata.RemoteClusterReference) bool {
	ret := _m.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for IsSame")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*metadata.RemoteClusterReference) bool); ok {
		r0 = rf(ref)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RemoteAgentMetadata_IsSame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSame'
type RemoteAgentMetadata_IsSame_Call struct {
	*mock.Call
}

// IsSame is a helper method to define mock.On call
//   - ref *metadata.RemoteClusterReference
func (_e *RemoteAgentMetadata_Expecter) IsSame(ref interface{}) *RemoteAgentMetadata_IsSame_Call {
	return &RemoteAgentMetadata_IsSame_Call{Call: _e.mock.On("IsSame", ref)}
}

func (_c *RemoteAgentMetadata_IsSame_Call) Run(run func(ref *metadata.RemoteClusterReference)) *RemoteAgentMetadata_IsSame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*metadata.RemoteClusterReference))
	})
	return _c
}

func (_c *RemoteAgentMetadata_IsSame_Call) Return(_a0 bool) *RemoteAgentMetadata_IsSame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RemoteAgentMetadata_IsSame_Call) RunAndReturn(run func(*metadata.RemoteClusterReference) bool) *RemoteAgentMetadata_IsSame_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *RemoteAgentMetadata) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoteAgentMetadata_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type RemoteAgentMetadata_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) Name() *RemoteAgentMetadata_Name_Call {
	return &RemoteAgentMetadata_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *RemoteAgentMetadata_Name_Call) Run(run func()) *RemoteAgentMetadata_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_Name_Call) Return(_a0 string) *RemoteAgentMetadata_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RemoteAgentMetadata_Name_Call) RunAndReturn(run func() string) *RemoteAgentMetadata_Name_Call {
	_c.Call.Return(run)
	return _c
}

// UsesAlternateAddress provides a mock function with no fields
func (_m *RemoteAgentMetadata) UsesAlternateAddress() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UsesAlternateAddress")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteAgentMetadata_UsesAlternateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UsesAlternateAddress'
type RemoteAgentMetadata_UsesAlternateAddress_Call struct {
	*mock.Call
}

// UsesAlternateAddress is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) UsesAlternateAddress() *RemoteAgentMetadata_UsesAlternateAddress_Call {
	return &RemoteAgentMetadata_UsesAlternateAddress_Call{Call: _e.mock.On("UsesAlternateAddress")}
}

func (_c *RemoteAgentMetadata_UsesAlternateAddress_Call) Run(run func()) *RemoteAgentMetadata_UsesAlternateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_UsesAlternateAddress_Call) Return(_a0 bool, _a1 error) *RemoteAgentMetadata_UsesAlternateAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RemoteAgentMetadata_UsesAlternateAddress_Call) RunAndReturn(run func() (bool, error)) *RemoteAgentMetadata_UsesAlternateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Uuid provides a mock function with no fields
func (_m *RemoteAgentMetadata) Uuid() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Uuid")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoteAgentMetadata_Uuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uuid'
type RemoteAgentMetadata_Uuid_Call struct {
	*mock.Call
}

// Uuid is a helper method to define mock.On call
func (_e *RemoteAgentMetadata_Expecter) Uuid() *RemoteAgentMetadata_Uuid_Call {
	return &RemoteAgentMetadata_Uuid_Call{Call: _e.mock.On("Uuid")}
}

func (_c *RemoteAgentMetadata_Uuid_Call) Run(run func()) *RemoteAgentMetadata_Uuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RemoteAgentMetadata_Uuid_Call) Return(_a0 string) *RemoteAgentMetadata_Uuid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RemoteAgentMetadata_Uuid_Call) RunAndReturn(run func() string) *RemoteAgentMetadata_Uuid_Call {
	_c.Call.Return(run)
	return _c
}

// NewRemoteAgentMetadata creates a new instance of RemoteAgentMetadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteAgentMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteAgentMetadata {
	mock := &RemoteAgentMetadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
