// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	metadata "github.com/couchbase/goxdcr/metadata"

	mock "github.com/stretchr/testify/mock"
)

// AgentSrcManifestGetter is an autogenerated mock type for the AgentSrcManifestGetter type
type AgentSrcManifestGetter struct {
	mock.Mock
}

type AgentSrcManifestGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentSrcManifestGetter) EXPECT() *AgentSrcManifestGetter_Expecter {
	return &AgentSrcManifestGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: forceRefresh
func (_m *AgentSrcManifestGetter) Execute(forceRefresh bool) *metadata.CollectionsManifest {
	ret := _m.Called(forceRefresh)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *metadata.CollectionsManifest
	if rf, ok := ret.Get(0).(func(bool) *metadata.CollectionsManifest); ok {
		r0 = rf(forceRefresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.CollectionsManifest)
		}
	}

	return r0
}

// AgentSrcManifestGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AgentSrcManifestGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - forceRefresh bool
func (_e *AgentSrcManifestGetter_Expecter) Execute(forceRefresh interface{}) *AgentSrcManifestGetter_Execute_Call {
	return &AgentSrcManifestGetter_Execute_Call{Call: _e.mock.On("Execute", forceRefresh)}
}

func (_c *AgentSrcManifestGetter_Execute_Call) Run(run func(forceRefresh bool)) *AgentSrcManifestGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *AgentSrcManifestGetter_Execute_Call) Return(_a0 *metadata.CollectionsManifest) *AgentSrcManifestGetter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AgentSrcManifestGetter_Execute_Call) RunAndReturn(run func(bool) *metadata.CollectionsManifest) *AgentSrcManifestGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentSrcManifestGetter creates a new instance of AgentSrcManifestGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentSrcManifestGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentSrcManifestGetter {
	mock := &AgentSrcManifestGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
