package mocks

import (
	metadata "github.com/couchbase/goxdcr/metadata"
	mock "github.com/stretchr/testify/mock"
)

// CollectionsManifestOps is an autogenerated mock type for the CollectionsManifestOps type
type CollectionsManifestOps struct {
	mock.Mock
}

// CollectionManifestGetter provides a mock function with given fields: bucketName
func (_m *CollectionsManifestOps) CollectionManifestGetter(bucketName string) (*metadata.CollectionsManifest, error) {
	ret := _m.Called(bucketName)

	var r0 *metadata.CollectionsManifest
	if rf, ok := ret.Get(0).(func(string) *metadata.CollectionsManifest); ok {
		r0 = rf(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata.CollectionsManifest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bucketName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
