// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecrementerFunc is an autogenerated mock type for the DecrementerFunc type
type DecrementerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: shaString
func (_m *DecrementerFunc) Execute(shaString string) {
	_m.Called(shaString)
}
