// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	service_def "github.com/couchbase/goxdcr/service_def"
	mock "github.com/stretchr/testify/mock"
)

// EventLogSvc is an autogenerated mock type for the EventLogSvc type
type EventLogSvc struct {
	mock.Mock
}

// WriteEvent provides a mock function with given fields: eventId, args
func (_m *EventLogSvc) WriteEvent(eventId service_def.EventIdType, args map[string]string) {
	_m.Called(eventId, args)
}

// NewEventLogSvc creates a new instance of EventLogSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventLogSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventLogSvc {
	mock := &EventLogSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
