// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	base "github.com/couchbase/goxdcr/v8/base"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/couchbase/goxdcr/v8/utils"
)

// BucketStatsOps is an autogenerated mock type for the BucketStatsOps type
type BucketStatsOps struct {
	mock.Mock
}

type BucketStatsOps_Expecter struct {
	mock *mock.Mock
}

func (_m *BucketStatsOps) EXPECT() *BucketStatsOps_Expecter {
	return &BucketStatsOps_Expecter{mock: &_m.Mock}
}

// GetFailoverLog provides a mock function with given fields: requestOpts, dataTransferCtx
func (_m *BucketStatsOps) GetFailoverLog(requestOpts *base.FailoverLogRequest, dataTransferCtx *utils.Context) (*base.BucketFailoverLog, base.ErrorMap, error) {
	ret := _m.Called(requestOpts, dataTransferCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetFailoverLog")
	}

	var r0 *base.BucketFailoverLog
	var r1 base.ErrorMap
	var r2 error
	if rf, ok := ret.Get(0).(func(*base.FailoverLogRequest, *utils.Context) (*base.BucketFailoverLog, base.ErrorMap, error)); ok {
		return rf(requestOpts, dataTransferCtx)
	}
	if rf, ok := ret.Get(0).(func(*base.FailoverLogRequest, *utils.Context) *base.BucketFailoverLog); ok {
		r0 = rf(requestOpts, dataTransferCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*base.BucketFailoverLog)
		}
	}

	if rf, ok := ret.Get(1).(func(*base.FailoverLogRequest, *utils.Context) base.ErrorMap); ok {
		r1 = rf(requestOpts, dataTransferCtx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(base.ErrorMap)
		}
	}

	if rf, ok := ret.Get(2).(func(*base.FailoverLogRequest, *utils.Context) error); ok {
		r2 = rf(requestOpts, dataTransferCtx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BucketStatsOps_GetFailoverLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFailoverLog'
type BucketStatsOps_GetFailoverLog_Call struct {
	*mock.Call
}

// GetFailoverLog is a helper method to define mock.On call
//   - requestOpts *base.FailoverLogRequest
//   - dataTransferCtx *utils.Context
func (_e *BucketStatsOps_Expecter) GetFailoverLog(requestOpts interface{}, dataTransferCtx interface{}) *BucketStatsOps_GetFailoverLog_Call {
	return &BucketStatsOps_GetFailoverLog_Call{Call: _e.mock.On("GetFailoverLog", requestOpts, dataTransferCtx)}
}

func (_c *BucketStatsOps_GetFailoverLog_Call) Run(run func(requestOpts *base.FailoverLogRequest, dataTransferCtx *utils.Context)) *BucketStatsOps_GetFailoverLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*base.FailoverLogRequest), args[1].(*utils.Context))
	})
	return _c
}

func (_c *BucketStatsOps_GetFailoverLog_Call) Return(_a0 *base.BucketFailoverLog, _a1 base.ErrorMap, _a2 error) *BucketStatsOps_GetFailoverLog_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *BucketStatsOps_GetFailoverLog_Call) RunAndReturn(run func(*base.FailoverLogRequest, *utils.Context) (*base.BucketFailoverLog, base.ErrorMap, error)) *BucketStatsOps_GetFailoverLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetVBucketStats provides a mock function with given fields: requestOpts, dataTransferCtx
func (_m *BucketStatsOps) GetVBucketStats(requestOpts *base.VBucketStatsRequest, dataTransferCtx *utils.Context) (*base.BucketVBStats, base.ErrorMap, error) {
	ret := _m.Called(requestOpts, dataTransferCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetVBucketStats")
	}

	var r0 *base.BucketVBStats
	var r1 base.ErrorMap
	var r2 error
	if rf, ok := ret.Get(0).(func(*base.VBucketStatsRequest, *utils.Context) (*base.BucketVBStats, base.ErrorMap, error)); ok {
		return rf(requestOpts, dataTransferCtx)
	}
	if rf, ok := ret.Get(0).(func(*base.VBucketStatsRequest, *utils.Context) *base.BucketVBStats); ok {
		r0 = rf(requestOpts, dataTransferCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*base.BucketVBStats)
		}
	}

	if rf, ok := ret.Get(1).(func(*base.VBucketStatsRequest, *utils.Context) base.ErrorMap); ok {
		r1 = rf(requestOpts, dataTransferCtx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(base.ErrorMap)
		}
	}

	if rf, ok := ret.Get(2).(func(*base.VBucketStatsRequest, *utils.Context) error); ok {
		r2 = rf(requestOpts, dataTransferCtx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BucketStatsOps_GetVBucketStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVBucketStats'
type BucketStatsOps_GetVBucketStats_Call struct {
	*mock.Call
}

// GetVBucketStats is a helper method to define mock.On call
//   - requestOpts *base.VBucketStatsRequest
//   - dataTransferCtx *utils.Context
func (_e *BucketStatsOps_Expecter) GetVBucketStats(requestOpts interface{}, dataTransferCtx interface{}) *BucketStatsOps_GetVBucketStats_Call {
	return &BucketStatsOps_GetVBucketStats_Call{Call: _e.mock.On("GetVBucketStats", requestOpts, dataTransferCtx)}
}

func (_c *BucketStatsOps_GetVBucketStats_Call) Run(run func(requestOpts *base.VBucketStatsRequest, dataTransferCtx *utils.Context)) *BucketStatsOps_GetVBucketStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*base.VBucketStatsRequest), args[1].(*utils.Context))
	})
	return _c
}

func (_c *BucketStatsOps_GetVBucketStats_Call) Return(_a0 *base.BucketVBStats, _a1 base.ErrorMap, _a2 error) *BucketStatsOps_GetVBucketStats_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *BucketStatsOps_GetVBucketStats_Call) RunAndReturn(run func(*base.VBucketStatsRequest, *utils.Context) (*base.BucketVBStats, base.ErrorMap, error)) *BucketStatsOps_GetVBucketStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewBucketStatsOps creates a new instance of BucketStatsOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketStatsOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketStatsOps {
	mock := &BucketStatsOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
