// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	base "github.com/couchbase/goxdcr/base"
	crMeta "github.com/couchbase/goxdcr/crMeta"

	log "github.com/couchbase/goxdcr/log"

	mock "github.com/stretchr/testify/mock"
)

// ConflictResolver is an autogenerated mock type for the ConflictResolver type
type ConflictResolver struct {
	mock.Mock
}

type ConflictResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *ConflictResolver) EXPECT() *ConflictResolver_Expecter {
	return &ConflictResolver_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: source, target, logger
func (_m *ConflictResolver) Execute(source *crMeta.Metadata, target *crMeta.Metadata, logger *log.CommonLogger) (base.ConflictResult, error) {
	ret := _m.Called(source, target, logger)

	var r0 base.ConflictResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*crMeta.Metadata, *crMeta.Metadata, *log.CommonLogger) (base.ConflictResult, error)); ok {
		return rf(source, target, logger)
	}
	if rf, ok := ret.Get(0).(func(*crMeta.Metadata, *crMeta.Metadata, *log.CommonLogger) base.ConflictResult); ok {
		r0 = rf(source, target, logger)
	} else {
		r0 = ret.Get(0).(base.ConflictResult)
	}

	if rf, ok := ret.Get(1).(func(*crMeta.Metadata, *crMeta.Metadata, *log.CommonLogger) error); ok {
		r1 = rf(source, target, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConflictResolver_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ConflictResolver_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - source *crMeta.Metadata
//   - target *crMeta.Metadata
//   - logger *log.CommonLogger
func (_e *ConflictResolver_Expecter) Execute(source interface{}, target interface{}, logger interface{}) *ConflictResolver_Execute_Call {
	return &ConflictResolver_Execute_Call{Call: _e.mock.On("Execute", source, target, logger)}
}

func (_c *ConflictResolver_Execute_Call) Run(run func(source *crMeta.Metadata, target *crMeta.Metadata, logger *log.CommonLogger)) *ConflictResolver_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*crMeta.Metadata), args[1].(*crMeta.Metadata), args[2].(*log.CommonLogger))
	})
	return _c
}

func (_c *ConflictResolver_Execute_Call) Return(_a0 base.ConflictResult, _a1 error) *ConflictResolver_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConflictResolver_Execute_Call) RunAndReturn(run func(*crMeta.Metadata, *crMeta.Metadata, *log.CommonLogger) (base.ConflictResult, error)) *ConflictResolver_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewConflictResolver creates a new instance of ConflictResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConflictResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConflictResolver {
	mock := &ConflictResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
