// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	common "github.com/couchbase/goxdcr/v8/common"
	metadata "github.com/couchbase/goxdcr/v8/metadata"

	mock "github.com/stretchr/testify/mock"
)

// SourceNozzle is an autogenerated mock type for the SourceNozzle type
type SourceNozzle struct {
	mock.Mock
}

type SourceNozzle_Expecter struct {
	mock *mock.Mock
}

func (_m *SourceNozzle) EXPECT() *SourceNozzle_Expecter {
	return &SourceNozzle_Expecter{mock: &_m.Mock}
}

// AsyncComponentEventListeners provides a mock function with given fields:
func (_m *SourceNozzle) AsyncComponentEventListeners() map[string]common.AsyncComponentEventListener {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsyncComponentEventListeners")
	}

	var r0 map[string]common.AsyncComponentEventListener
	if rf, ok := ret.Get(0).(func() map[string]common.AsyncComponentEventListener); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]common.AsyncComponentEventListener)
		}
	}

	return r0
}

// SourceNozzle_AsyncComponentEventListeners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncComponentEventListeners'
type SourceNozzle_AsyncComponentEventListeners_Call struct {
	*mock.Call
}

// AsyncComponentEventListeners is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) AsyncComponentEventListeners() *SourceNozzle_AsyncComponentEventListeners_Call {
	return &SourceNozzle_AsyncComponentEventListeners_Call{Call: _e.mock.On("AsyncComponentEventListeners")}
}

func (_c *SourceNozzle_AsyncComponentEventListeners_Call) Run(run func()) *SourceNozzle_AsyncComponentEventListeners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_AsyncComponentEventListeners_Call) Return(_a0 map[string]common.AsyncComponentEventListener) *SourceNozzle_AsyncComponentEventListeners_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_AsyncComponentEventListeners_Call) RunAndReturn(run func() map[string]common.AsyncComponentEventListener) *SourceNozzle_AsyncComponentEventListeners_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *SourceNozzle) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type SourceNozzle_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Close() *SourceNozzle_Close_Call {
	return &SourceNozzle_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *SourceNozzle_Close_Call) Run(run func()) *SourceNozzle_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Close_Call) Return(_a0 error) *SourceNozzle_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Close_Call) RunAndReturn(run func() error) *SourceNozzle_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connector provides a mock function with given fields:
func (_m *SourceNozzle) Connector() common.Connector {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connector")
	}

	var r0 common.Connector
	if rf, ok := ret.Get(0).(func() common.Connector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Connector)
		}
	}

	return r0
}

// SourceNozzle_Connector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connector'
type SourceNozzle_Connector_Call struct {
	*mock.Call
}

// Connector is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Connector() *SourceNozzle_Connector_Call {
	return &SourceNozzle_Connector_Call{Call: _e.mock.On("Connector")}
}

func (_c *SourceNozzle_Connector_Call) Run(run func()) *SourceNozzle_Connector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Connector_Call) Return(_a0 common.Connector) *SourceNozzle_Connector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Connector_Call) RunAndReturn(run func() common.Connector) *SourceNozzle_Connector_Call {
	_c.Call.Return(run)
	return _c
}

// Connectors provides a mock function with given fields:
func (_m *SourceNozzle) Connectors() []common.Connector {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connectors")
	}

	var r0 []common.Connector
	if rf, ok := ret.Get(0).(func() []common.Connector); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Connector)
		}
	}

	return r0
}

// SourceNozzle_Connectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connectors'
type SourceNozzle_Connectors_Call struct {
	*mock.Call
}

// Connectors is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Connectors() *SourceNozzle_Connectors_Call {
	return &SourceNozzle_Connectors_Call{Call: _e.mock.On("Connectors")}
}

func (_c *SourceNozzle_Connectors_Call) Run(run func()) *SourceNozzle_Connectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Connectors_Call) Return(_a0 []common.Connector) *SourceNozzle_Connectors_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Connectors_Call) RunAndReturn(run func() []common.Connector) *SourceNozzle_Connectors_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with given fields:
func (_m *SourceNozzle) Id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SourceNozzle_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type SourceNozzle_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Id() *SourceNozzle_Id_Call {
	return &SourceNozzle_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *SourceNozzle_Id_Call) Run(run func()) *SourceNozzle_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Id_Call) Return(_a0 string) *SourceNozzle_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Id_Call) RunAndReturn(run func() string) *SourceNozzle_Id_Call {
	_c.Call.Return(run)
	return _c
}

// IsOpen provides a mock function with given fields:
func (_m *SourceNozzle) IsOpen() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsOpen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SourceNozzle_IsOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOpen'
type SourceNozzle_IsOpen_Call struct {
	*mock.Call
}

// IsOpen is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) IsOpen() *SourceNozzle_IsOpen_Call {
	return &SourceNozzle_IsOpen_Call{Call: _e.mock.On("IsOpen")}
}

func (_c *SourceNozzle_IsOpen_Call) Run(run func()) *SourceNozzle_IsOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_IsOpen_Call) Return(_a0 bool) *SourceNozzle_IsOpen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_IsOpen_Call) RunAndReturn(run func() bool) *SourceNozzle_IsOpen_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields:
func (_m *SourceNozzle) Open() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type SourceNozzle_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Open() *SourceNozzle_Open_Call {
	return &SourceNozzle_Open_Call{Call: _e.mock.On("Open")}
}

func (_c *SourceNozzle_Open_Call) Run(run func()) *SourceNozzle_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Open_Call) Return(_a0 error) *SourceNozzle_Open_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Open_Call) RunAndReturn(run func() error) *SourceNozzle_Open_Call {
	_c.Call.Return(run)
	return _c
}

// RaiseEvent provides a mock function with given fields: event
func (_m *SourceNozzle) RaiseEvent(event *common.Event) {
	_m.Called(event)
}

// SourceNozzle_RaiseEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaiseEvent'
type SourceNozzle_RaiseEvent_Call struct {
	*mock.Call
}

// RaiseEvent is a helper method to define mock.On call
//   - event *common.Event
func (_e *SourceNozzle_Expecter) RaiseEvent(event interface{}) *SourceNozzle_RaiseEvent_Call {
	return &SourceNozzle_RaiseEvent_Call{Call: _e.mock.On("RaiseEvent", event)}
}

func (_c *SourceNozzle_RaiseEvent_Call) Run(run func(event *common.Event)) *SourceNozzle_RaiseEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*common.Event))
	})
	return _c
}

func (_c *SourceNozzle_RaiseEvent_Call) Return() *SourceNozzle_RaiseEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *SourceNozzle_RaiseEvent_Call) RunAndReturn(run func(*common.Event)) *SourceNozzle_RaiseEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function with given fields: data
func (_m *SourceNozzle) Receive(data interface{}) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type SourceNozzle_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - data interface{}
func (_e *SourceNozzle_Expecter) Receive(data interface{}) *SourceNozzle_Receive_Call {
	return &SourceNozzle_Receive_Call{Call: _e.mock.On("Receive", data)}
}

func (_c *SourceNozzle_Receive_Call) Run(run func(data interface{})) *SourceNozzle_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *SourceNozzle_Receive_Call) Return(_a0 error) *SourceNozzle_Receive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Receive_Call) RunAndReturn(run func(interface{}) error) *SourceNozzle_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RecycleDataObj provides a mock function with given fields: obj
func (_m *SourceNozzle) RecycleDataObj(obj interface{}) {
	_m.Called(obj)
}

// SourceNozzle_RecycleDataObj_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecycleDataObj'
type SourceNozzle_RecycleDataObj_Call struct {
	*mock.Call
}

// RecycleDataObj is a helper method to define mock.On call
//   - obj interface{}
func (_e *SourceNozzle_Expecter) RecycleDataObj(obj interface{}) *SourceNozzle_RecycleDataObj_Call {
	return &SourceNozzle_RecycleDataObj_Call{Call: _e.mock.On("RecycleDataObj", obj)}
}

func (_c *SourceNozzle_RecycleDataObj_Call) Run(run func(obj interface{})) *SourceNozzle_RecycleDataObj_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *SourceNozzle_RecycleDataObj_Call) Return() *SourceNozzle_RecycleDataObj_Call {
	_c.Call.Return()
	return _c
}

func (_c *SourceNozzle_RecycleDataObj_Call) RunAndReturn(run func(interface{})) *SourceNozzle_RecycleDataObj_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterComponentEventListener provides a mock function with given fields: eventType, listener
func (_m *SourceNozzle) RegisterComponentEventListener(eventType common.ComponentEventType, listener common.ComponentEventListener) error {
	ret := _m.Called(eventType, listener)

	if len(ret) == 0 {
		panic("no return value specified for RegisterComponentEventListener")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.ComponentEventType, common.ComponentEventListener) error); ok {
		r0 = rf(eventType, listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_RegisterComponentEventListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterComponentEventListener'
type SourceNozzle_RegisterComponentEventListener_Call struct {
	*mock.Call
}

// RegisterComponentEventListener is a helper method to define mock.On call
//   - eventType common.ComponentEventType
//   - listener common.ComponentEventListener
func (_e *SourceNozzle_Expecter) RegisterComponentEventListener(eventType interface{}, listener interface{}) *SourceNozzle_RegisterComponentEventListener_Call {
	return &SourceNozzle_RegisterComponentEventListener_Call{Call: _e.mock.On("RegisterComponentEventListener", eventType, listener)}
}

func (_c *SourceNozzle_RegisterComponentEventListener_Call) Run(run func(eventType common.ComponentEventType, listener common.ComponentEventListener)) *SourceNozzle_RegisterComponentEventListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.ComponentEventType), args[1].(common.ComponentEventListener))
	})
	return _c
}

func (_c *SourceNozzle_RegisterComponentEventListener_Call) Return(_a0 error) *SourceNozzle_RegisterComponentEventListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_RegisterComponentEventListener_Call) RunAndReturn(run func(common.ComponentEventType, common.ComponentEventListener) error) *SourceNozzle_RegisterComponentEventListener_Call {
	_c.Call.Return(run)
	return _c
}

// ResponsibleVBs provides a mock function with given fields:
func (_m *SourceNozzle) ResponsibleVBs() []uint16 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResponsibleVBs")
	}

	var r0 []uint16
	if rf, ok := ret.Get(0).(func() []uint16); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint16)
		}
	}

	return r0
}

// SourceNozzle_ResponsibleVBs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResponsibleVBs'
type SourceNozzle_ResponsibleVBs_Call struct {
	*mock.Call
}

// ResponsibleVBs is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) ResponsibleVBs() *SourceNozzle_ResponsibleVBs_Call {
	return &SourceNozzle_ResponsibleVBs_Call{Call: _e.mock.On("ResponsibleVBs")}
}

func (_c *SourceNozzle_ResponsibleVBs_Call) Run(run func()) *SourceNozzle_ResponsibleVBs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_ResponsibleVBs_Call) Return(_a0 []uint16) *SourceNozzle_ResponsibleVBs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_ResponsibleVBs_Call) RunAndReturn(run func() []uint16) *SourceNozzle_ResponsibleVBs_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnector provides a mock function with given fields: connector
func (_m *SourceNozzle) SetConnector(connector common.Connector) error {
	ret := _m.Called(connector)

	if len(ret) == 0 {
		panic("no return value specified for SetConnector")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.Connector) error); ok {
		r0 = rf(connector)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_SetConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnector'
type SourceNozzle_SetConnector_Call struct {
	*mock.Call
}

// SetConnector is a helper method to define mock.On call
//   - connector common.Connector
func (_e *SourceNozzle_Expecter) SetConnector(connector interface{}) *SourceNozzle_SetConnector_Call {
	return &SourceNozzle_SetConnector_Call{Call: _e.mock.On("SetConnector", connector)}
}

func (_c *SourceNozzle_SetConnector_Call) Run(run func(connector common.Connector)) *SourceNozzle_SetConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Connector))
	})
	return _c
}

func (_c *SourceNozzle_SetConnector_Call) Return(_a0 error) *SourceNozzle_SetConnector_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_SetConnector_Call) RunAndReturn(run func(common.Connector) error) *SourceNozzle_SetConnector_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: settings
func (_m *SourceNozzle) Start(settings metadata.ReplicationSettingsMap) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.ReplicationSettingsMap) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type SourceNozzle_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - settings metadata.ReplicationSettingsMap
func (_e *SourceNozzle_Expecter) Start(settings interface{}) *SourceNozzle_Start_Call {
	return &SourceNozzle_Start_Call{Call: _e.mock.On("Start", settings)}
}

func (_c *SourceNozzle_Start_Call) Run(run func(settings metadata.ReplicationSettingsMap)) *SourceNozzle_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.ReplicationSettingsMap))
	})
	return _c
}

func (_c *SourceNozzle_Start_Call) Return(_a0 error) *SourceNozzle_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Start_Call) RunAndReturn(run func(metadata.ReplicationSettingsMap) error) *SourceNozzle_Start_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with given fields:
func (_m *SourceNozzle) State() common.PartState {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 common.PartState
	if rf, ok := ret.Get(0).(func() common.PartState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(common.PartState)
	}

	return r0
}

// SourceNozzle_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type SourceNozzle_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) State() *SourceNozzle_State_Call {
	return &SourceNozzle_State_Call{Call: _e.mock.On("State")}
}

func (_c *SourceNozzle_State_Call) Run(run func()) *SourceNozzle_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_State_Call) Return(_a0 common.PartState) *SourceNozzle_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_State_Call) RunAndReturn(run func() common.PartState) *SourceNozzle_State_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *SourceNozzle) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type SourceNozzle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *SourceNozzle_Expecter) Stop() *SourceNozzle_Stop_Call {
	return &SourceNozzle_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *SourceNozzle_Stop_Call) Run(run func()) *SourceNozzle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceNozzle_Stop_Call) Return(_a0 error) *SourceNozzle_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_Stop_Call) RunAndReturn(run func() error) *SourceNozzle_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UnRegisterComponentEventListener provides a mock function with given fields: eventType, listener
func (_m *SourceNozzle) UnRegisterComponentEventListener(eventType common.ComponentEventType, listener common.ComponentEventListener) error {
	ret := _m.Called(eventType, listener)

	if len(ret) == 0 {
		panic("no return value specified for UnRegisterComponentEventListener")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.ComponentEventType, common.ComponentEventListener) error); ok {
		r0 = rf(eventType, listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_UnRegisterComponentEventListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnRegisterComponentEventListener'
type SourceNozzle_UnRegisterComponentEventListener_Call struct {
	*mock.Call
}

// UnRegisterComponentEventListener is a helper method to define mock.On call
//   - eventType common.ComponentEventType
//   - listener common.ComponentEventListener
func (_e *SourceNozzle_Expecter) UnRegisterComponentEventListener(eventType interface{}, listener interface{}) *SourceNozzle_UnRegisterComponentEventListener_Call {
	return &SourceNozzle_UnRegisterComponentEventListener_Call{Call: _e.mock.On("UnRegisterComponentEventListener", eventType, listener)}
}

func (_c *SourceNozzle_UnRegisterComponentEventListener_Call) Run(run func(eventType common.ComponentEventType, listener common.ComponentEventListener)) *SourceNozzle_UnRegisterComponentEventListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.ComponentEventType), args[1].(common.ComponentEventListener))
	})
	return _c
}

func (_c *SourceNozzle_UnRegisterComponentEventListener_Call) Return(_a0 error) *SourceNozzle_UnRegisterComponentEventListener_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_UnRegisterComponentEventListener_Call) RunAndReturn(run func(common.ComponentEventType, common.ComponentEventListener) error) *SourceNozzle_UnRegisterComponentEventListener_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function with given fields: settings
func (_m *SourceNozzle) UpdateSettings(settings metadata.ReplicationSettingsMap) error {
	ret := _m.Called(settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.ReplicationSettingsMap) error); ok {
		r0 = rf(settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SourceNozzle_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type SourceNozzle_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - settings metadata.ReplicationSettingsMap
func (_e *SourceNozzle_Expecter) UpdateSettings(settings interface{}) *SourceNozzle_UpdateSettings_Call {
	return &SourceNozzle_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", settings)}
}

func (_c *SourceNozzle_UpdateSettings_Call) Run(run func(settings metadata.ReplicationSettingsMap)) *SourceNozzle_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.ReplicationSettingsMap))
	})
	return _c
}

func (_c *SourceNozzle_UpdateSettings_Call) Return(_a0 error) *SourceNozzle_UpdateSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SourceNozzle_UpdateSettings_Call) RunAndReturn(run func(metadata.ReplicationSettingsMap) error) *SourceNozzle_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewSourceNozzle creates a new instance of SourceNozzle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourceNozzle(t interface {
	mock.TestingT
	Cleanup(func())
}) *SourceNozzle {
	mock := &SourceNozzle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
