// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PipelineProgressRecorder is an autogenerated mock type for the PipelineProgressRecorder type
type PipelineProgressRecorder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: progress
func (_m *PipelineProgressRecorder) Execute(progress string) {
	_m.Called(progress)
}
