package mocks

import (
	common "github.com/couchbase/goxdcr/common"
	mock "github.com/stretchr/testify/mock"
)

// SupervisorFailureHandler is an autogenerated mock type for the SupervisorFailureHandler type
type SupervisorFailureHandler struct {
	mock.Mock
}

// OnError provides a mock function with given fields: supervisor, errors
func (_m *SupervisorFailureHandler) OnError(supervisor common.Supervisor, errors map[string]error) {
	_m.Called(supervisor, errors)
}
